[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "config_router"
version = "0.1.0"
dependencies = [
    "amaranth[builtin-yosys]",
    "yowasp-yosys>=0.51.0.0.post872",
]

[tool.uv.sources]
amaranth = { git = "https://github.com/amaranth-lang/amaranth" }
